baseURL = 'https://github.com/paulb00th/galapagos/'
languageCode = 'en-us'
title = 'Galapagos Dive Academy'
theme = 'hugo-universal-theme'

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true
    
# Logo

[params]

logo = "img/gda-logo.png"
logo_small = "img/gda-logo.png"
about_us = "<p>Galapagos Dive Academy<br/>Marchena 177 y Adolfo Hanny<br/>Santa Cruz<br/>200350<br/>Puerto Ayora<br/>Ecuador</p>"

[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Our Diving"
    identifier = "menu.our-diving"
    weight     = 2

[[menu.main]]
    name       = "Our Diving"
    weight     = 1
    parent     = "menu.our-diving"
    url        = "/our-diving/our-diving"

[[menu.main]]
    name       = "Our main dive sites"
    weight     = 2
    parent     = "menu.our-diving"
    url        = "/our-diving/our-main-dive-sites"

[[menu.main]]
    name       = "Our other day dive sites"
    weight     = 3
    parent     = "menu.our-diving"
    url        = "/our-diving/our-other-day-dive-sites"

[[menu.main]]
    name       = "Liveaboards"
    weight     = 4
    parent     = "menu.our-diving"
    url        = "/our-diving/liveaboards"

[[menu.main]]
    name       = "Our boats"
    weight     = 5
    parent     = "menu.our-diving"
    url        = "/our-diving/our-boats"

[[menu.main]]
    name       = "Our Prices"
    weight     = 6
    parent     = "menu.our-diving"
    url        = "/our-diving/our-prices"

[[menu.main]]
    name       = "Accom/Travel"
    identifier = "menu.acommodation"
    weight     = 3
    url        = "/accom-travel"

[[menu.main]]
    name       = "Tours"
    identifier = "menu.tours"
    weight     = 4
    url        = "/tours"

[[menu.main]]
    name       = "Visiting"
    identifier = "menu.visit"
    weight     = 5

[[menu.main]]
    name       = "Introuction"
    weight     = 1
    parent     = "menu.visit"
    url        = "/visiting/introduction"

[[menu.main]]
    name       = "Plan your trip"
    weight     = 2
    parent     = "menu.visit"    
    url        = "/visiting/plan-your-trip"

[[menu.main]]
    name       = "Climate & dive conditions"
    weight     = 3
    parent     = "menu.visit"
    url        = "/visiting/climate-and-dive-conditions"

[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    weight     = 6

[[menu.main]]
    name       = "Introduction"
    weight     = 1
    parent     = "menu.about"
    url        = "/about/introduction"

[[menu.main]]
    name       = "Gallery"
    weight     = 2
    parent     = "menu.about"  
    url        = "/about/gallery"  

[[menu.main]]
    name       = "Terms & conditions"
    weight     = 3
    parent     = "menu.about"
    url        = "/about/terms-and-conditions" 

[[menu.main]]
    name       = "Contact"
    identifier = "menu.contact"
    weight     = 7
    url        = "/contact" 

# Top bar social links menu

[params.topbar]
    enable = true
    text = "<p>Cell: <a href='tel:+593-98-5848720'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email: info@GalapagosDiveAcademy.com</p>"

# Footer

[params.clients]
    enable = true
    title = "Our Clients"
    subtitle = ""
